services:
  - type: web
    name: wakfu-companion-server
    runtime: docker
    rootDir: server
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000
